-- Additive campaign migration; never rerun fixture scripts to upgrade.
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE AGENTSHIELD_WH;
CREATE SCHEMA IF NOT EXISTS AGENTSHIELD_DB.ORCH;
CREATE STAGE IF NOT EXISTS AGENTSHIELD_DB.ORCH.CODE;

CREATE TABLE IF NOT EXISTS AGENTSHIELD_DB.CORE.CAMPAIGN_MUTEX (
  ID INTEGER NOT NULL, VERSION INTEGER NOT NULL
);
-- Deployment is single-writer. Runtime admissions UPDATE this existing row.
INSERT INTO AGENTSHIELD_DB.CORE.CAMPAIGN_MUTEX
SELECT 1, 0 WHERE NOT EXISTS (SELECT 1 FROM AGENTSHIELD_DB.CORE.CAMPAIGN_MUTEX);

CREATE TABLE IF NOT EXISTS AGENTSHIELD_DB.CORE.CAMPAIGNS (
  CAMPAIGN_ID VARCHAR NOT NULL, REQUEST_KEY VARCHAR NOT NULL,
  REQUEST_HASH VARCHAR NOT NULL, REQUEST VARIANT NOT NULL, STATUS VARCHAR NOT NULL,
  PARENT_CAMPAIGN_ID VARCHAR, REQUESTED_BY VARCHAR,
  TARGET_SPEC VARIANT, TARGET_HASH VARCHAR, SURFACE VARIANT,
  SUMMARY VARIANT, REPORT_HTML VARCHAR, PROPOSAL VARIANT, REASON VARCHAR,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS AGENTSHIELD_DB.CORE.CAMPAIGN_JOBS (
  JOB_ID VARCHAR NOT NULL, CAMPAIGN_ID VARCHAR NOT NULL, CATEGORY VARCHAR NOT NULL,
  SLOT INTEGER NOT NULL, EXPECTED_CASES INTEGER NOT NULL, STATUS VARCHAR NOT NULL,
  CLAIM_ID VARCHAR, AGENT_RUN_ID VARCHAR, REASON VARCHAR,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS AGENTSHIELD_DB.CORE.CAMPAIGN_CASES (
  CASE_ID VARCHAR NOT NULL, JOB_ID VARCHAR NOT NULL, CAMPAIGN_ID VARCHAR NOT NULL,
  CATEGORY VARCHAR NOT NULL, ORDINAL INTEGER NOT NULL, STATE VARCHAR NOT NULL,
  PAYLOAD VARIANT, PARENT_CASE_ID VARCHAR, ATTEMPT_ID VARCHAR,
  VERDICT VARCHAR, REASON VARCHAR, RESULT_SUMMARY VARIANT,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- No public grants: raw prompts and retained evidence stay administrator-only.