-- On-demand graph; root stays unscheduled. Never deploy while a campaign runs.
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE AGENTSHIELD_WH;
CREATE TASK IF NOT EXISTS AGENTSHIELD_DB.ORCH.CAMPAIGN_ROOT
  WAREHOUSE = AGENTSHIELD_WH USER_TASK_TIMEOUT_MS = 3600000
  AS CALL AGENTSHIELD_DB.ORCH.PREPARE_CAMPAIGN();
CREATE TASK IF NOT EXISTS AGENTSHIELD_DB.ORCH.CAMPAIGN_SLOT_0
  WAREHOUSE = AGENTSHIELD_WH USER_TASK_TIMEOUT_MS = 3600000
  AFTER AGENTSHIELD_DB.ORCH.CAMPAIGN_ROOT
  AS CALL AGENTSHIELD_DB.ORCH.CAMPAIGN_WORKER(0);
CREATE TASK IF NOT EXISTS AGENTSHIELD_DB.ORCH.CAMPAIGN_SLOT_1
  WAREHOUSE = AGENTSHIELD_WH USER_TASK_TIMEOUT_MS = 3600000
  AFTER AGENTSHIELD_DB.ORCH.CAMPAIGN_ROOT
  AS CALL AGENTSHIELD_DB.ORCH.CAMPAIGN_WORKER(1);
CREATE TASK IF NOT EXISTS AGENTSHIELD_DB.ORCH.CAMPAIGN_FINISH
  WAREHOUSE = AGENTSHIELD_WH USER_TASK_TIMEOUT_MS = 600000
  FINALIZE = AGENTSHIELD_DB.ORCH.CAMPAIGN_ROOT
  AS CALL AGENTSHIELD_DB.ORCH.FINALIZE_CAMPAIGN();
ALTER TASK AGENTSHIELD_DB.ORCH.CAMPAIGN_SLOT_0 RESUME;
ALTER TASK AGENTSHIELD_DB.ORCH.CAMPAIGN_SLOT_1 RESUME;
ALTER TASK AGENTSHIELD_DB.ORCH.CAMPAIGN_FINISH RESUME;