-- Additive remediation-apply migration. Apply is reachable only through
-- ORCH.PREPARE_REMEDIATION / APPLY_REMEDIATION / ROLLBACK_REMEDIATION, never via
-- CAMPAIGN_API or the orchestrator agent tool.
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE AGENTSHIELD_WH;

-- Pins apply to the account this migration ran in; a clone/replica elsewhere fails closed.
CREATE TABLE IF NOT EXISTS AGENTSHIELD_DB.CORE.REMEDIATION_SETTINGS (
  EXPECTED_ACCOUNT VARCHAR NOT NULL
);
INSERT INTO AGENTSHIELD_DB.CORE.REMEDIATION_SETTINGS
SELECT CURRENT_ACCOUNT() WHERE NOT EXISTS (SELECT 1 FROM AGENTSHIELD_DB.CORE.REMEDIATION_SETTINGS);

CREATE TABLE IF NOT EXISTS AGENTSHIELD_DB.CORE.REMEDIATION_APPLIES (
  APPLY_ID VARCHAR NOT NULL, CAMPAIGN_ID VARCHAR NOT NULL, KIND VARCHAR NOT NULL,
  RECIPE_ID VARCHAR NOT NULL, TARGET VARCHAR NOT NULL,
  PROPOSAL_HASH VARCHAR NOT NULL, TARGET_HASH_BEFORE VARCHAR NOT NULL, TARGET_HASH_AFTER VARCHAR,
  STATUS VARCHAR NOT NULL, CONFIRM_TOKEN_HASH VARCHAR NOT NULL,
  TOKEN_EXPIRES_AT TIMESTAMP_LTZ NOT NULL, CONSUMED_AT TIMESTAMP_LTZ,
  PREPARED_BY VARCHAR, APPLIED_BY VARCHAR, APPLIED_ROLE VARCHAR, CLIENT_RECEIPT VARCHAR,
  SPEC_BEFORE VARIANT, SPEC_AFTER VARIANT, ROLLBACK_OF VARCHAR, RETEST_CAMPAIGN_ID VARCHAR, REASON VARCHAR,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- No public grants: specs and tokens hashes are administrator-only.
