-- Additive upgrade. Deploy with the task graph idle.
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE AGENTSHIELD_WH;
ALTER TABLE AGENTSHIELD_DB.CORE.CAMPAIGNS ADD COLUMN IF NOT EXISTS BATCH_ID VARCHAR;
ALTER TABLE AGENTSHIELD_DB.CORE.CAMPAIGNS ADD COLUMN IF NOT EXISTS TARGET VARCHAR;
UPDATE AGENTSHIELD_DB.CORE.CAMPAIGNS SET TARGET = REQUEST:target::STRING WHERE TARGET IS NULL;
ALTER TABLE AGENTSHIELD_DB.CORE.CAMPAIGN_JOBS ADD COLUMN IF NOT EXISTS STARTED_AT TIMESTAMP_LTZ;
ALTER TABLE AGENTSHIELD_DB.CORE.CAMPAIGN_JOBS ADD COLUMN IF NOT EXISTS COMPLETED_AT TIMESTAMP_LTZ;
CREATE TABLE IF NOT EXISTS AGENTSHIELD_DB.CORE.CAMPAIGN_BATCHES (
  BATCH_ID VARCHAR NOT NULL, REQUEST_KEY VARCHAR NOT NULL, REQUEST_HASH VARCHAR NOT NULL,
  REQUEST VARIANT NOT NULL, STATUS VARCHAR NOT NULL, SUMMARY VARIANT, REPORT_HTML VARCHAR,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS AGENTSHIELD_DB.CORE.CAMPAIGN_SETTINGS (ID INTEGER, WORKER_COUNT INTEGER);
INSERT INTO AGENTSHIELD_DB.CORE.CAMPAIGN_SETTINGS
SELECT 1, 4 WHERE NOT EXISTS (SELECT 1 FROM AGENTSHIELD_DB.CORE.CAMPAIGN_SETTINGS);