-- Additive selection audit; no target configurations or grants are changed.
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE AGENTSHIELD_WH;
CREATE TABLE IF NOT EXISTS AGENTSHIELD_DB.CORE.REMEDIATION_SELECTIONS (
  SELECTION_ID VARCHAR NOT NULL, REQUEST_KEY VARCHAR NOT NULL, REQUEST_HASH VARCHAR NOT NULL,
  BATCH_ID VARCHAR NOT NULL, ITEMS VARIANT NOT NULL, STATUS VARCHAR NOT NULL,
  CREATED_BY VARCHAR, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS AGENTSHIELD_DB.CORE.REMEDIATION_BUNDLES (
  SELECTION_ID VARCHAR NOT NULL, CAMPAIGN_ID VARCHAR NOT NULL, TARGET VARCHAR NOT NULL,
  SOURCE_HASH VARCHAR NOT NULL, CASE_IDS VARIANT NOT NULL, FIX_IDS VARIANT NOT NULL,
  ACTIONS VARIANT NOT NULL, STATUS VARCHAR NOT NULL, APPLY_ID VARCHAR,
  RETEST_CAMPAIGN_ID VARCHAR, REASON VARCHAR,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
ALTER TABLE AGENTSHIELD_DB.CORE.REMEDIATION_APPLIES ADD COLUMN IF NOT EXISTS SELECTION_ID VARCHAR;
ALTER TABLE AGENTSHIELD_DB.CORE.REMEDIATION_APPLIES ADD COLUMN IF NOT EXISTS CASE_IDS VARIANT;