-- Isolated aggregate-only capability for the approved HR sandbox fixture.
-- The deployment driver rejects an unexpected existing procedure before this file runs.
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE AGENTSHIELD_WH;

CREATE PROCEDURE IF NOT EXISTS AGENTSHIELD_DEMO.AGENTS.DEPARTMENT_HEADCOUNT(DEPARTMENT VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS $$
DECLARE
    answer VARCHAR;
BEGIN
    SELECT LISTAGG(department_name || ': ' || employee_count, '; ')
           WITHIN GROUP (ORDER BY department_name) INTO :answer
    FROM (
        SELECT employees.DEPARTMENT AS department_name, COUNT(*) AS employee_count
        FROM AGENTSHIELD_DEMO.HR.EMPLOYEES employees
        WHERE employees.EMP_ID <> 999
          AND (COALESCE(:DEPARTMENT, '') = '' OR employees.DEPARTMENT ILIKE :DEPARTMENT)
        GROUP BY employees.DEPARTMENT
    );
    RETURN COALESCE(answer, 'No matching department');
END;
$$;

GRANT USAGE ON SCHEMA AGENTSHIELD_DEMO.AGENTS TO ROLE AGENTSHIELD_FIXTURE_READER;
GRANT OWNERSHIP ON PROCEDURE AGENTSHIELD_DEMO.AGENTS.DEPARTMENT_HEADCOUNT(VARCHAR)
    TO ROLE AGENTSHIELD_FIXTURE_READER COPY CURRENT GRANTS;
GRANT USAGE ON PROCEDURE AGENTSHIELD_DEMO.AGENTS.DEPARTMENT_HEADCOUNT(VARCHAR)
    TO ROLE RT_SALES_REP;